<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Customer_model extends CI_Model
{

    public $table = 'customer';
    public $table_detail = 'customer_details';
    public $id = 'kdcust';
    public $custid = 'customer_kdcust';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        //$this->db->where($this->id, $id);
        $this->db->select('*');
        $this->db->from('customer');
        $this->db->join('customer_details','customer_details.customer_kdcust = customer.kdcust');
        $hasil = $this->db->get()->row();
        return $hasil;
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kdcust', $q);
	$this->db->or_like('salutation', $q);
	$this->db->or_like('first_name', $q);
	$this->db->or_like('last_name', $q);
	$this->db->or_like('display_name', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('website', $q);
	$this->db->or_like('company_name', $q);
	$this->db->or_like('currency', $q);
	$this->db->or_like('payment_terms', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kdcust', $q);
	$this->db->or_like('salutation', $q);
	$this->db->or_like('first_name', $q);
	$this->db->or_like('last_name', $q);
	$this->db->or_like('display_name', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('website', $q);
	$this->db->or_like('company_name', $q);
	$this->db->or_like('currency', $q);
	$this->db->or_like('payment_terms', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // insert data komplit
    function insertdetail($datadetail)
    {
        $this->db->insert($this->table_detail, $datadetail);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // update data
    function updatedetail($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Customer_model.php */
/* Location: ./application/models/Customer_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-21 23:35:29 */
/* http://harviacode.com */