<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Customer_details_model extends CI_Model
{

    public $table = 'customer_details';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('', $q);
	$this->db->or_like('customer_id', $q);
	$this->db->or_like('bill_addr_street', $q);
	$this->db->or_like('bill_addr_city', $q);
	$this->db->or_like('bill_addr_state', $q);
	$this->db->or_like('bill_addr_zip_code', $q);
	$this->db->or_like('bill_addr_country', $q);
	$this->db->or_like('bill_addr_phone', $q);
	$this->db->or_like('bill_addr_fax', $q);
	$this->db->or_like('ship_addr_street', $q);
	$this->db->or_like('ship_addr_city', $q);
	$this->db->or_like('ship_addr_state', $q);
	$this->db->or_like('ship_addr_zip_code', $q);
	$this->db->or_like('ship_addr_country', $q);
	$this->db->or_like('ship_addr_phone', $q);
	$this->db->or_like('ship_addr_fax', $q);
	$this->db->or_like('notes', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
	$this->db->or_like('customer_id', $q);
	$this->db->or_like('bill_addr_street', $q);
	$this->db->or_like('bill_addr_city', $q);
	$this->db->or_like('bill_addr_state', $q);
	$this->db->or_like('bill_addr_zip_code', $q);
	$this->db->or_like('bill_addr_country', $q);
	$this->db->or_like('bill_addr_phone', $q);
	$this->db->or_like('bill_addr_fax', $q);
	$this->db->or_like('ship_addr_street', $q);
	$this->db->or_like('ship_addr_city', $q);
	$this->db->or_like('ship_addr_state', $q);
	$this->db->or_like('ship_addr_zip_code', $q);
	$this->db->or_like('ship_addr_country', $q);
	$this->db->or_like('ship_addr_phone', $q);
	$this->db->or_like('ship_addr_fax', $q);
	$this->db->or_like('notes', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Customer_details_model.php */
/* Location: ./application/models/Customer_details_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-21 23:36:30 */
/* http://harviacode.com */