<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Delivery_notice_model extends CI_Model
{

    public $table = 'delivery_notice';
    public $table_detail = 'delivery_notice_details';
    public $id = 'kddelnot';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, intval($id));
        return $this->db->get($this->table)->row();
    }

    function get_by_id_detail($id)
    {
        $this->db->where($this->id, intval($id));
        return $this->db->get($this->table_detail)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kddelnot', $q);
	$this->db->or_like('kdinv', $q);
	$this->db->or_like('kdquo', $q);
	$this->db->or_like('custkd', $q);
	$this->db->or_like('delnotdate', $q);
	$this->db->or_like('custnotes', $q);
	$this->db->or_like('remark', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kddelnot', $q);
	$this->db->or_like('kdinv', $q);
	$this->db->or_like('kdquo', $q);
	$this->db->or_like('custkd', $q);
	$this->db->or_like('delnotdate', $q);
	$this->db->or_like('custnotes', $q);
	$this->db->or_like('remark', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insertdetail($datadetail)
    {
        $this->db->insert_batch($this->table_detail, $datadetail);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Delivery_notice_model.php */
/* Location: ./application/models/Delivery_notice_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-02-05 00:29:44 */
/* http://harviacode.com */