<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Groups_model extends CI_Model
{

    public $table = 'groups';
    public $id = 'id';
    public $order = 'DESC';
    public $orderawal = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->orderawal);
        return $this->db->get($this->table)->result();
    }

    function get_user_group()
    {
        $sql = "SELECT a.*,b.*
                FROM groups a
                LEFT JOIN users_groups b ON b.group_id=a.id";
        return $this->db->query($sql)->result();
    }

    // get all query
    function get_all_query()
    {
        $sql = "SELECT a.*, b.name AS groupname, b.description, c.name as permissname
                FROM groups_permissions a
                LEFT JOIN groups b ON a.group_id=b.id
                LEFT JOIN permissions c ON a.permission_id=c.id";
        return $this->db->query($sql)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('description', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('description', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Groups_model.php */
/* Location: ./application/models/Groups_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-21 23:40:15 */
/* http://harviacode.com */