<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Payment_received_model extends CI_Model
{

    public $table = 'payment_received';
    public $id = 'kdpayrec';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, intval($id));
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kdpayrec', $q);
	$this->db->or_like('kdinv', $q);
	$this->db->or_like('kdquo', $q);
	$this->db->or_like('custkd', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('bankcharge', $q);
	$this->db->or_like('paydate', $q);
	$this->db->or_like('paymode', $q);
	$this->db->or_like('reference', $q);
	$this->db->or_like('remark', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kdpayrec', $q);
	$this->db->or_like('kdinv', $q);
	$this->db->or_like('kdquo', $q);
	$this->db->or_like('custkd', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('bankcharge', $q);
	$this->db->or_like('paydate', $q);
	$this->db->or_like('paymode', $q);
	$this->db->or_like('reference', $q);
	$this->db->or_like('remark', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Payment_received_model.php */
/* Location: ./application/models/Payment_received_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-25 23:38:35 */
/* http://harviacode.com */